### PR TITLE
adding mock file for realtime utils

### PR DESCRIPTION
**Pull request by rupamJoshi**
## Relevant Documentation Links
-

## Relevant Jira Links
-
-

## Other Relevant PRs
-

## Changes

(Description of changes)

### Changes Include

-   [ ] Bug fix 🐛 (non-breaking change which fixes an issue)
-   [ ] New feature ✨ (non-breaking change which adds functionality)
-   [ ] Breaking change 😢 (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Refactor ⚒️ (code change that neither fixes a bug nor adds a feature)
-   [ ] Tooling ⚙️ (Changes to the build process or auxiliary tools and libraries such as documentation generation)
-   [ ] Performance ⚡ (code change that improves performance)

### Checklist

-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Requires migrations
-   [ ] Requires dependency update
-   [ ] Breaking API Change
-   [ ] I have added proper logs for production debugging
-   [ ] I have added performance (APM) monitoring checkpoints
-   [ ] I have added unit tests

## Screenshots (if any)
(prefer animated gif)

### Test #1

Description

- [ ] Acceptance Creteria #1
- [ ] Acceptance Creteria #2

### CODE REVIEW

**Review by aashishAil — APPROVED** [review]

**Review by krishnamurthypranesh — CHANGES_REQUESTED** [review]
Unless these mocks are for testing the code in backbone, which I don't think its, we should not be exposing mocks from backbone to our services. This is for the following reasons:
    1. Mocks are part of the tests. If we don't maintain our mocks as part of the tests, then our tests won't be idempotent.
    2. This defeats the purpose of mocking. We won't be able to manage side effects (which can vary per-service) if we do this.
    
Please move this to the repo where it's being used.

**Comment by aashishAil** [comment]
@krishnamurthypranesh I am of the completely opposite opinion
- For point #1 we are going to add test cases in ```backbone``` itself. It is going to form the core piece and having this without test cases seems rhetorical to our complete exercise of making code testable
- For point #2 we are already having the controlling the outcome of the mock file in our code, so don't really get how we'll lose out on maintaining the side-effects on a service level?

**Comment by krishnamurthypranesh** [comment]
> @krishnamurthypranesh I am of the completely opposite opinion
> 
> * For point [add title in rewards #1](https://github.com/CreatorStack/backbone/pull/1) we are going to add test cases in `backbone` itself. It is going to form the core piece and having this without test cases seems rhetorical to our complete exercise of making code testable
> * For point [downgraded to 1.13 #2](https://github.com/CreatorStack/backbone/pull/2) we are already having the controlling the outcome of the mock file in our code, so don't really get how we'll lose out on maintaining the side-effects on a service level?

We can add test cases in `backbone` but, we shouldn't be using the same mocks outside. But, we shouldn't be exposing mocks for the tests we write in backbone to the code which calls backbone. Backbone shouldn't dictate how the mocks are used.

What I mean by side-effects is that we might want to change the behaviour of the mock injected at run based on different services. Like, there are many functions in which we modify the behaviour of a pointer in the mocked function/method/interface at run time as part of the test.

**Review by MrDHat — APPROVED** [review]

**Comment by MrDHat** [comment]
Approving the changes but please conclude the discussion b/w @aashishAil &amp; @krishnamurthypranesh before merging

**Comment by aashishAil** [comment]
For that I am in agreement @krishnamurthypranesh 

@rupamJoshi Can you create a local implementation of mock in community. We can leave the current mock as is

**Pull request merged**
